ArchiveDemo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@show')->name('welcome');

Route::get('/clients/datatable', 'Admin\ClientController@datatable')->name('clients.datatable');
Route::resource('clients', 'Admin\ClientController', ['only' => ['index', 'store', 'show']]);

Route::resource('files', 'Admin\FileController', ['only' => ['edit', 'update']]);
Route::resource('files', 'Client\FileController', ['only' => ['index', 'create', 'store']]);

Route::post('/files/{path}/download', 'FileController@download')->name('files.download');
Route::get('/files/datatable/{userId}', 'FileController@datatable')->name('files.datatable');

Auth::routes();

ArchiveDemo/app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    protected $fillable = [
        "number", "date", "typeId", "path", "clientId", "isFilled"
    ];

    // Relations
    public function client()
    {
        return $this->belongsTo(User::class, 'clientId');
    }

    public function type()
    {
        return $this->belongsTo(FileType::class, 'typeId');
    }

    public function invoice()
    {
        return $this->hasOne(Invoice::class, 'id');
    }

    public function bankStatement()
    {
        return $this->hasOne(BankStatement::class, 'id');
    }

    public function creditNote()
    {
        return $this->hasOne(CreditNote::class, 'id');
    }

    // Helper functions
    public function getFilePath()
    {
        return $this->path;
    }
}

ArchiveDemo/app/FileType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FileType extends Model
{
    // Relations
    public function files()
    {
        return $this->hasMany(File::class, 'typeId');
    }
}

ArchiveDemo/app/Http/Controllers/Admin/FileController.php
<?php

namespace App\Http\Controllers\Admin;

use App\BankStatement;
use App\CreditNote;
use App\Currency;
use App\File;
use App\FileType;
use App\Http\Controllers\Controller;
use App\Http\Requests\UpdateFile;
use App\Invoice;
use App\PaymentMethod;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('checkAdmin');
    }

    public function edit(File $file)
    {
        $this->authorize('update-file', $file);

        $file = $file->with('invoice', 'bankStatement', 'creditNote', 'client')->get()->where('id', $file->id)->first();

        $fileTypes = FileType::all();
        $paymentMethods = PaymentMethod::all();
        $currencies = Currency::all();

        return view('admin.file.edit', compact( 'file', 'fileTypes', 'paymentMethods', 'currencies'));
    }

    public function update(File $file, UpdateFile $request)
    {
        $attributes = $request->validated();
        $attributes['isFilled'] = array_key_exists('isFilled', $attributes) ? true : false;

        $attributes['typeId'] === "1" ? Invoice::updateOrCreate(
            ['id' => $file->id],
            ['id' => $file->id,
            'taxBase' => $attributes['tax-base'],
            'currencyId' => $attributes['currencyId'],
            'vat' => array_key_exists('vat', $attributes) && $attributes['vat'] === "on" ? true : false,
            'price' => $attributes['price']]
        ) : Invoice::where('id', $file->id)->delete();

        $attributes['typeId'] === "2" ? BankStatement::updateOrCreate(
            ['id' => $file->id],
            ['id' => $file->id,
            'bankName' => $attributes['bank-name'],
            'iban' => $attributes['iban']]
        ) : BankStatement::where('id', $file->id)->delete();;

        $attributes['typeId'] === "3" ? CreditNote::updateOrCreate(
            ['id' => $file->id],
            ['id' => $file->id,
            'paymentMethodId' => $attributes['paymentMethodId'],
            'note' => $attributes['note']]
        ) : CreditNote::where('id', $file->id)->delete();;

        $file->update($attributes);

        return redirect(route('clients.show', $file->client->id));
    }
}

ArchiveDemo/app/Http/Controllers/Client/FileController.php
<?php

namespace App\Http\Controllers\Client;

use App\File;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('checkClient');
    }

    public function index()
    {
        return view('file.index');
    }

    public function create()
    {
        return view('file.create');
    }

    public function store(Request $request)
    {
        $file = $request->file('file');

        File::create([
            'path' => Storage::disk('public')->put('/', $file),
            'clientId' => auth()->user()->id
        ]);
    }

}

ArchiveDemo/app/Http/Controllers/FileController.php
<?php

namespace App\Http\Controllers;

use App\File;
use App\Http\Requests\DownloadFile;
use App\User;
use Illuminate\Support\Facades\Response;
use Yajra\DataTables\Facades\DataTables;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function download(DownloadFile $request)
    {
        $file = File::where('path', $request->route('path'))->first();
        $client = $file->client->companyName;

        $ext = pathinfo($file->path, PATHINFO_EXTENSION);

        return Response::download("clientFiles/".$file->path, "$client-$file->id-archive-info.$ext");
    }

    public function datatable()
    {
        $this->authorize('index-file', $_GET['userId']);

        $user = User::find($_GET['userId']);

        $files = $user->files()->with('type');

        return DataTables::of($files)
            ->addColumn('action', function ($file) {
                return view('file.partials.actions', compact('file'));
            })
            ->rawColumns(['action'])
            ->make(true);
    }
}

ArchiveDemo/resources/views/file/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-10">
        <div class="card m2">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                        Upload Files
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <form method="post" action="{{route('files.store')}}" enctype="multipart/form-data" class="dropzone" id="dropzone">
                    @csrf
                </form>
            </div>
        </div>
    </div>
@endsection

ArchiveDemo/resources/views/file/index.blade.php
@extends('layouts.app')

@section('scripts')
    <script src="{{ asset('js/file/index.js') }}"></script>
@endsection

@section('content')
    <div class="col-md-10">
        <div class="card m2">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                        Your Files
                    </div>
                    <div class="text-md-right">
                        <a class="btn btn-primary" href="{{route('files.create')}}">Add Files</a>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <input type="hidden" id="user-id" value="{{auth()->user()->id}}">
                <table id="files-table" class="display" style="width:100%">
                    <thead>
                    <tr>
                        <th>Number</th>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection