ArchiveDemo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GuestController@show')->name('welcome');

Route::get('/clients/datatable', 'Admin\ClientController@datatable')->name('clients.datatable');
Route::resource('clients', 'Admin\ClientController', ['only' => ['index', 'store', 'show']]);

Route::resource('files', 'Admin\FileController', ['only' => ['edit', 'update']]);
Route::resource('files', 'Client\FileController', ['only' => ['index', 'create', 'store']]);

Route::post('/files/{path}/download', 'FileController@download')->name('files.download');
Route::get('/files/datatable/{userId}', 'FileController@datatable')->name('files.datatable');

Auth::routes();

ArchiveDemo/app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreClient;
use App\Mail\ContactClient;
use App\Role;
use App\User;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class ClientController extends Controller
{
    public function __construct()
    {
        $this->middleware('checkAdmin');
    }

    public function index()
    {
        return view('admin.client.index');
    }

    public function datatable()
    {
        $clients = auth()->user()->clients();

        return DataTables::of($clients)
            ->addColumn('unfilled-files', function ($client) {
                return $client->unfilledFilesCount();
            })
            ->addColumn('action', function ($client) {
                return view('admin.client.partials.view', compact('client'));
            })
            ->rawColumns(['action'])
            ->make(true);
    }

    public function store(StoreClient $request)
    {
        $attributes = $request->validated();

        // Generate random password for client
        $clientPass = Str::random(8);

        // Create client
        $user = User::create([
            'companyName' => $attributes['company-name'],
            'uic' => $attributes['uic'],
            'email' => $attributes['email'],
            'password' => Hash::make($clientPass),
            'accountingAdminId' => auth()->user()->id
        ]);
        $user->assignRole(Role::find(1));

        // Send email to client with password
        Mail::to($attributes['email'])
            ->send(new ContactClient($clientPass, auth()->user()));

        return back();
    }

    public function show(User $client) {
        $this->authorize('show-client', $client);

        return view('admin.client.show', compact('client'));
    }


}

ArchiveDemo/app/Http/Controllers/Client/FileController.php
<?php

namespace App\Http\Controllers\Client;

use App\File;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;

class FileController extends Controller
{
    public function __construct()
    {
        $this->middleware('checkClient');
    }

    public function index()
    {
        return view('file.index');
    }

    public function create()
    {
        return view('file.create');
    }

    public function store(Request $request)
    {
        $file = $request->file('file');

        File::create([
            'path' => Storage::disk('public')->put('/', $file),
            'clientId' => auth()->user()->id
        ]);
    }

}

ArchiveDemo/resources/views/admin/client/create.blade.php
<div id="addClientForm" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    &times;</button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{route('clients.store')}}">
                    @csrf
                    <div class="form-group row">
                        <label for="company-name" class="col-md-4 col-form-label text-md-right">{{ __('Company Name') }}</label>

                        <div class="col-md-6">
                            <input id="company-name" type="text" class="form-control @error('company-name') is-invalid @enderror" name="company-name" value="{{ old('company-name') }}" required autocomplete="company-name" autofocus>

                            @error('company-name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="uic" class="col-md-4 col-form-label text-md-right">{{ __('UIC') }}</label>

                        <div class="col-md-6">
                            <input id="uic" type="text" class="form-control @error('uic') is-invalid @enderror" name="uic" value="{{ old('uic') }}" required autocomplete="uic" autofocus>

                            @error('uic')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Add client</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ArchiveDemo/resources/views/admin/client/index.blade.php
@extends('layouts.app')

@section('scripts')
    <script src="{{ asset('js/admin/client/index.js') }}"></script>
@endsection

@section('content')
    <div class="col-md-10">
        <div class="card m2">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                        Your Clients
                    </div>
                    <div class="text-md-right">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addClientForm">Add client</button>
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <table id="clients-table" class="display" style="width:100%">
                    <thead>
                    <tr>
                        <th>Company Name</th>
                        <th>Email</th>
                        <th>UIC</th>
                        <th>Unfilled Files</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    @include('admin.client.create')
@endsection

ArchiveDemo/resources/views/admin/client/show.blade.php
@extends('layouts.app')

@section('scripts')
    <script src="{{ asset('js/file/index.js') }}"></script>
@endsection

@section('content')
    <div class="col-md-10">
        <div class="card m2">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-10">
                        {{$client->companyName}}'s data
                    </div>
                </div>
            </div>
            <div class="card-body text-center">
                <p><b>Company Name:</b> {{$client->companyName}}</p>
                <p><b>UIC:</b> {{$client->uic}}</p>
                <p><b>Email:</b> {{$client->email}}</p>
                <input type="hidden" id="user-id" value="{{$client->id}}">
                <table id="files-table" class="display mt-3" style="width:100%">
                    <thead>
                    <tr>
                        <th>Number</th>
                        <th>Date</th>
                        <th>Type</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection